### ISSUE TITLE
Unable to clone the repo

### ISSUE THREAD

**Issue by Woodhousemelena** [arjenv/omnikstats#6]
Cant clone your repo as per 
sudo git clone https://github.com/arjen/omnikstats.git

Without entering a USERNAME and PASSWORD..... What's up?

**Comment by Beacha** [comment]
The repo is wrong (also in the readme.md) should be 
https://github.com/arjenv/omnikstats.git

**Comment by Woodhousemelena** [comment]
Ahhh that fixed it... Great! Thanks

**Comment by Beacha** [comment]
You´re welcome. 

mmh now to close this issue. It´s a long time since I did something on github. 
Where or how  can I close this issue?
