### ISSUE TITLE
Cant get OmnikExport working

### ISSUE THREAD

**Issue by hlubach** [arjenv/omnikstats#7]
Moest Libreeleec er nieuw opzetten ,daardoor oude Omnik dir overschreven.
Nu weer een nieuwe aangemaakt.maar krijg nu de volgende mededeling als  ik python OmnikExport.py invoer.

LibreELEC:~/omnik # python OmnikExport.py
2017-02-04 10:04:51,549 DEBUG Importing output plugin 
Traceback (most recent call last):
  File "OmnikExport.py", line 185, in <module>
    omnik_exporter.run()
  File "OmnikExport.py", line 66, in run
    __import__(plugin_name)
ValueError: Empty module name
Dus nu gaan er geen gegevens naar Pvoutput

**Comment by Beacha** [comment]
I think you´re at the wrong place, this is not a Python program it is written in C.
